# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'VS2017-Win2016'

steps:
- bash: choco install -y wget
  displayName: 'Install wget'
- bash: |
    # Detect number of CPU cores
    export NUMCORES=`nproc`
    echo Using $NUMCORES cores
    # Download and prepare boost (only if not already present from cache)
    if [ ! -d "/tmp/boost_1_58_0" ]; then
      echo "Didn't find boost in cache. Downloading and building."
      wget -O /tmp/boost.zip http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.zip
      if [ $(sha512sum /tmp/boost.zip | awk '{print $1;}') == "e27b4b4687743b40ce1c45c262f64ac64bb0e122411b186e9e49d9e23bbfcf271f92ca9ca8b97abeb897f22e17e82e6744cc7433fccf904eb6d6f8ce204bcc4f" ]; then
        echo Correct sha512sum
      else
        echo Wrong sha512sum
        sha512sum boost.zip
        exit 1
      fi
      echo Extracting...
      unzip /tmp/boost.zip -d /tmp
      rm -rf boost.zip
      cd /tmp/boost_1_58_0
      ./bootstrap.sh --with-toolset=msvc --with-libraries=filesystem,thread,chrono,program_options
      cat bootstrap.log
      cd ..
    else
      echo Found boost in cache. Use cache and build.
    fi
    # Compile and install boost (if cached, this should be fast)
    cd /tmp/boost_1_58_0
    ./b2 toolset=msvc link=static cxxflags=-fPIC -d0 -j$NUMCORES install
  displayName: 'Install Boost'

- bash: choco install -y dokany --version 1.1.0.2000 --installargs INSTALLDEVFILES=1 || exit 0
  displayName: 'Install DokanY'

- task: CMake@1
  inputs:
    cmakeArgs: .. -DBUILD_TESTING=on
